<?php
/*
    Proxy Norfolk Cultural Art Feed
    Copyright (C) 2014 Code for Hampton Roads contributors

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

    $title = 'Norfolk public art exhibits';
    $this->headTitle($title);
?>
<h1>
    <?php echo $this->escapeHtml($title); ?>
</h1>

<p>
<a href="<?php echo $this->url('exhibit', ['action' => 'add']); ?>">
    Add new exhibit
</a>
</p>

<p>
    <?php
	use Zend\Json\Json;

	$list = [];
	foreach ($this->exhibits as $exhibit) {
	    $list[] = $exhibit;
	}
	echo Zend\Json\Json::prettyPrint(Zend\Json\Json::encode(['exhibit' => $list]));
    ?>
</p>
